# Generated by Django 2.1.2 on 2018-10-17 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_substance_e_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMoreInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('more_info', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='more_info',
        ),
        migrations.AddField(
            model_name='categorymoreinfo',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='more_info', to='api.Category'),
        ),
    ]
