# Generated by Django 2.1.2 on 2018-10-17 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181017_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategoryMoreInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('more_info', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SubstanceMoreInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('more_info', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='more_info',
        ),
        migrations.RemoveField(
            model_name='substance',
            name='more_info',
        ),
        migrations.AddField(
            model_name='substancemoreinfo',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='more_info', to='api.Substance'),
        ),
        migrations.AddField(
            model_name='subcategorymoreinfo',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='more_info', to='api.SubCategory'),
        ),
    ]
