# Generated by Django 2.1.2 on 2018-10-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181017_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substance',
            name='e_number',
            field=models.CharField(max_length=255),
        ),
    ]
