# Generated by Django 2.1.2 on 2018-10-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='substance',
            name='e_number',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
