# Generated by Django 2.1.2 on 2018-10-17 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181017_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='substancemoreinfo',
            old_name='sub_category',
            new_name='substance',
        ),
    ]
